### ISSUE TITLE
No execution

### ISSUE THREAD

**Issue by 007scorpio** [toyakula/luna#5]
Scan does not work after setting hostname and port

**Comment by toyakula** [comment]
Would you please describe in details

**Comment by toyakula** [comment]
Would you please describe in details？

**Comment by jiugong** [comment]
按照步骤操作爆这样的错误Traceback (most recent call last):
  File "luna.py", line 67, in <module>
    luna()
  File "luna.py", line 38, in luna
    ctn,mark,count = luna_file.readfile(header=1)
  File "/root/luna/lunafile.py", line 27, in readfile
    luna_log.log_fatal("Can not open file [%s]." %(self.filename))
  File "/root/luna/lunalog.py", line 30, in log_fatal
    self.log_error("fatal",text)
  File "/root/luna/lunalog.py", line 9, in log_error
    file = open(self.filename,'w+')
AttributeError: 'lunalog' object has no attribute 'filename'
请问怎么解决呢？
